<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Proletarier\Module'                  => __DIR__ . '/Module.php',
  'Proletarier\Broker'                  => __DIR__ . '/src/Proletarier/Broker.php',
  'Proletarier\Client'                  => __DIR__ . '/src/Proletarier/Client.php',
  'Proletarier\Controller\Proletarier'  => __DIR__ . '/src/Proletarier/Controller/Proletarier.php',
  'Proletarier\Event'                   => __DIR__ . '/src/Proletarier/Event.php',
  'Proletarier\EventManagerAwareTrait'  => __DIR__ . '/src/Proletarier/EventManagerAwareTrait.php',
  'Proletarier\Handler\AbstractHandler' => __DIR__ . '/src/Proletarier/Handler/AbstractHandler.php',
  'Proletarier\Handler\EventLogger'     => __DIR__ . '/src/Proletarier/Handler/EventLogger.php',
  'Proletarier\LoggingListener'         => __DIR__ . '/src/Proletarier/LoggingListener.php',
  'Proletarier\Worker\Worker'           => __DIR__ . '/src/Proletarier/Worker/Worker.php',
  'Proletarier\Worker\WorkerInterface'  => __DIR__ . '/src/Proletarier/Worker/WorkerInterface.php',
  'Proletarier\Worker\WorkerPool'       => __DIR__ . '/src/Proletarier/Worker/WorkerPool.php',
);
